# Auki internal cactus — base values (matterless-prod default deployment).
# image.repository is set by ArgoCD from terraform (internal-cactus ECR).

replicaCount: 1

image:
  pullPolicy: Always
  tag: latest

tolerations:
  - key: dedicated
    value: armGroup
    effect: NoSchedule

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/group.name: default
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'

resources:
  limits:
    memory: 300Mi
  requests:
    memory: 100Mi

useExistingSecret: true

entrypointPrefixes:
  - REACT_APP
  - EXPO_PUBLIC
entrypointEnvVars:
  - API_URL
  - DDS_URL
  - POCKETBASE_URL
  - AUKI_APP_KEY
  - AUKI_APP_SECRET
  - DS_URL
  - VEII_DEV_API_STORE_BRAND_ID
  - VEII_DEV_API_SECRET
  - VEII_DEV_API_USERNAME
  - VEII_DEV_API_PASSWORD
  - VEII_DEV_URL
  - VEII_DEV_STORE_CODE
  - CACTUS_ENABLE_PRODUCT_SCANNING
  - CACTUS_ENABLE_DEV_ANALYTICS
  - CACTUS_ENABLE_VEII
  - AMPLITUDE_DEV_API_KEY
  - AMPLITUDE_PROD_API_KEY
  - AUTH_ISSUER
  - AUTH_CLIENT_ID_WEB
  - JOYSTICK_API_KEY

envVars:
  EXPO_PUBLIC_DDS_URL: "https://dds.auki.network/"
  EXPO_PUBLIC_API_URL: "https://api.auki.network/"
  EXPO_PUBLIC_VEII_DEV_API_STORE_BRAND_ID: "10"
  EXPO_PUBLIC_VEII_DEV_URL: "http://172.16.99.28:1443/scheduler-main"
  EXPO_PUBLIC_VEII_DEV_STORE_CODE: "0001"
  EXPO_PUBLIC_CACTUS_ENABLE_PRODUCT_SCANNING: "true"
  EXPO_PUBLIC_CACTUS_ENABLE_DEV_ANALYTICS: "true"
  EXPO_PUBLIC_CACTUS_ENABLE_VEII: "false"
  NO_FLIPPER: "1"
  EXPO_PUBLIC_AUTH_ISSUER: "https://auth.auki.network"
  EXPO_PUBLIC_AUTH_CLIENT_ID_WEB: "342554035527680591"

secrets:
  cactus:
    as: envFrom
