# Auki internal cactus — dev environment.

image:
  pullPolicy: Always
  tag: latest

envVars:
  EXPO_PUBLIC_DDS_URL: "https://dds.dev.aukiverse.com/"
  EXPO_PUBLIC_API_URL: "https://api.dev.aukiverse.com/"
  EXPO_PUBLIC_AUTH_ISSUER: "https://auth.dev.aukiverse.com"
  EXPO_PUBLIC_AUTH_CLIENT_ID_WEB: "335028730298696300"
