name: Lint and Test Charts

on: pull_request

jobs:
  lint-test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        # https://github.com/kubernetes-sigs/kind/releases
        kind_version: [v0.30.0]
        k8s_version: [v1.34.0, v1.33.4, v1.32.8, v1.31.12]
        include:
          - kind_version: v0.22.0
            k8s_version: v1.29.2
          - kind_version: v0.22.0
            k8s_version: v1.23.17
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.19.0

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed="$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})"
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Run chart-testing (lint)
        run: ct lint --target-branch ${{ github.event.repository.default_branch }}

      - name: Create kind cluster
        uses: helm/kind-action@v1
        if: steps.list-changed.outputs.changed == 'true'
        with:
          version: ${{ matrix.kind_version }}
          node_image: kindest/node:${{ matrix.k8s_version }}
          kubectl_version: ${{ matrix.k8s_version }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.MATTERLESS_COMMON_AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.MATTERLESS_COMMON_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.MATTERLESS_COMMON_AWS_REGION }}

      - name: Run pre-install scripts
        if: steps.list-changed.outputs.changed == 'true'
        env:
          AUTH_JWT_PROFILE: ${{ secrets.AUTH_JWT_PROFILE }}
          APP_SECRET: ${{ secrets.APP_SECRET }}
          APP_KEY: ${{ secrets.APP_KEY }}
        run: find charts/*/scripts -name pre-install.sh -exec {} \;

      - name: Run chart-testing (install)
        if: steps.list-changed.outputs.changed == 'true'
        run: |
          # Workaround for https://github.com/helm/chart-testing/issues/655
          repos="$(yq '.dependencies[] | select(.repository != null) | "\(.name)=\(.repository)"' charts/*/Chart.yaml)"
          repo_args="$(echo "$repos" | sed '/^=$/d' | sort -t = -k 2 -u | awk '{printf "%s,", $0}' | sed 's/,$//')"
          test -n "$repo_args" && chart_repos="--chart-repos $repo_args" || chart_repos=""
          ct install --target-branch "${{ github.event.repository.default_branch }}" $chart_repos
